### ISSUE TITLE
Rename `unfolded` to `expanded`

### ISSUE THREAD

**Issue by tomekwi** [studio-b12/bare-select#1]
It’s a better name

**Comment by jzabroski** [comment]
Expanded is a synonym of Unfolded.
http://www.thesaurus.com/browse/unfold

Personally, I like unfold since its antonym is fold.  Plus, in computer science, fold/unfold are algebraic operators on "bulk data types" like lists.  Fold takes a list of things and returns a single atomic value, and unfold takes a single atomic value and returns a list of things.  In this sense, they are dual.

Plus, the terminology 'expand' gets hairy when you talk about virtualization of the items in the context of auto-completion.

Finally, in a soap box moment, it's much better naming than how some people call a Cue Banner/Placeholder a "watermark", as a watermark describes a permanent imprinting; unfolded still accurately describes the state of the control.

**Comment by tomekwi** [comment]
Fair enough, good points there! Thanks! We’ll leave it as it is then.
